spring:
  datasource:
    url: jdbc:oracle:thin:@182.237.126.19:1521:XE
    username: jdeveloper34
    password: jdeveloper34
  jpa:
    show-sql: true
    generate-ddl: true
    properties:
      hibernate:
        format-sql:true
    hibernate:
      ddl-auto: create